/**
 * 200 common 5-letter English words for the Wordle game.
 * Hardcoded — no database, no API. Both players get the same word via seeded RNG.
 */
export const WORDS: string[] = [
  "ABOUT","ABOVE","ABUSE","ACTOR","ACUTE","ADMIT","ADOPT","ADULT","AFTER","AGAIN",
  "AGENT","AGREE","AHEAD","ALARM","ALBUM","ALERT","ALIKE","ALIGN","ALIVE","ALLEY",
  "ALLOW","ALONE","ALONG","ALTER","ANGEL","ANGER","ANGLE","ANGRY","ANIME","ANKLE",
  "ANNEX","APPLE","APPLY","ARENA","ARGUE","ARISE","ARMOR","ARMY","AROMA","AROSE",
  "ARRAY","ARROW","ASIDE","ASKED","ATLAS","ATTIC","AUDIO","AUDIT","AVOID","AWAKE",
  "AWARD","AWARE","AWFUL","BADLY","BAKER","BADLY","BASIC","BASIS","BEACH","BEGAN",
  "BEGIN","BEING","BELOW","BENCH","BIBLE","BIRTH","BLACK","BLADE","BLAME","BLAND",
  "BLAST","BLAZE","BLEED","BLEND","BLESS","BLIND","BLOCK","BLOOD","BLOWN","BOARD",
  "BOOST","BOOTH","BOUND","BRAIN","BRAVE","BREAD","BREAK","BRING","BROKE","BROOK",
  "BRUSH","BUILD","BUILT","BUNCH","BURNS","BURST","BUYER","CABIN","CAMEL","CANDY",
  "CARGO","CARRY","CATCH","CAUSE","CEASE","CHAIN","CHAIR","CHAOS","CHARM","CHART",
  "CHASE","CHEAP","CHECK","CHEEK","CHESS","CHEST","CHIEF","CHILD","CHINA","CHOIR",
  "CHOSE","CIVIC","CIVIL","CLAIM","CLASS","CLEAN","CLEAR","CLIMB","CLING","CLOCK",
  "CLONE","CLOSE","CLOUD","COACH","COAST","CORAL","COULD","COUNT","COURT","COVER",
  "CRACK","CRAFT","CRANE","CRASH","CRAWL","CRAZY","CREAM","CRIME","CRISP","CROSS",
  "CROWD","CROWN","CRUSH","CURVE","CYCLE","DAILY","DANCE","DATUM","DEALT","DEBUT",
  "DECOY","DELAY","DELTA","DENSE","DEPOT","DEPTH","DERBY","DEVIL","DIRTY","DISCO",
  "DODGE","DOING","DOUBT","DOUGH","DRAFT","DRAIN","DRAKE","DRAMA","DRANK","DRAWN",
  "DREAM","DRESS","DRIFT","DRINK","DRIVE","DROVE","DYING","EAGER","EAGLE","EARLY",
];

/** All valid 5-letter guess words (superset of answers). */
export const VALID_GUESSES: Set<string> = new Set([
  ...WORDS,
  "AAHED","AALII","ABACI","ABACK","ABAFT","ABASE","ABASH","ABATE","ABBEY","ABBOT",
  "ABHOR","ABIDE","ABLER","ABODE","ABORT","ABRAM","ABRAY","ABRIS","ABSIT","ABUZZ",
  "ABYSS","ACNED","ACORN","ACIDS","ACHED","ACHES","ACHOO","ACTED","ACTIN","ACMES",
  "ADDED","ADDER","ADDLE","ADEPT","ADHERE","ADMAN","ADMIN","ADOBE","AEGIS","AEONS",
  "AFOOT","AFOUL","AFRAY","AFTER","AGAIN","AGATE","AGAVE","AGAZE","AGENE","AGED",
  "AGEDLY","AGILE","AGING","AGISM","AGIST","AGLOW","AGONE","AGONY","AGORA","AGUED",
  "AHOLD","AIDED","AIMER","AIOLI","AIRED","AIRER","AIRTS","AISLE","AITCH","AIVER",
  "ALLOW","ALMUG","ALOFT","ALOOF","ALOUD","ALPHA","ALTAR","AMBER","AMBLE","AMEND",
  "AMIDE","AMIGO","AMINO","AMISS","AMITY","AMOUR","AMPLE","AMUSE","ANGEL","ANNOY",
  "ANTIC","ANTSY","ANVIL","AORTA","APHID","APIAN","APISH","APNEA","APTLY","ARBOR",
]);
