import { createClient } from "@/lib/supabase/server";
import { NextResponse } from "next/server";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const PROMPTS: any[] = [
  // ─── DAILY (50) ─────────────────────────────────────────
  { category: "daily", question: "What's the smallest thing that made you smile today?" },
  { category: "daily", question: "If today had a color, what would it be and why?" },
  { category: "daily", question: "What's one thing you learned today that you didn't know yesterday?" },
  { category: "daily", question: "Describe your mood right now using only a weather report." },
  { category: "daily", question: "What song has been stuck in your head lately?" },
  { category: "daily", question: "If you could redo one moment from today, what would it be?" },
  { category: "daily", question: "What's something you're looking forward to in the next 48 hours?" },
  { category: "daily", question: "What's the last thing you ate that genuinely surprised you with how good it was?" },
  { category: "daily", question: "Who made you feel good today, even if just for a second?" },
  { category: "daily", question: "What would make tomorrow a 10/10 day for you?" },
  { category: "daily", question: "If your energy today were a battery, what percentage would it show?" },
  { category: "daily", question: "What's one small win you had today that deserves a celebration?" },
  { category: "daily", question: "What's a random thought that's been circling your mind all day?" },
  { category: "daily", question: "What scent, sound, or texture reminded you of a memory today?" },
  { category: "daily", question: "What's something you did today purely for yourself?" },
  { category: "daily", question: "If you could fast-forward time to any moment this week, what would it be?" },
  { category: "daily", question: "What's the last thing that made you genuinely laugh?" },
  { category: "daily", question: "What's one thing you'd tell your morning self before the day started?" },
  { category: "daily", question: "What's something you were kind to yourself about today?" },
  { category: "daily", question: "If today was a movie, what genre would it be?" },
  { category: "daily", question: "What's something you've been procrastinating on and why?" },
  { category: "daily", question: "What's the most beautiful thing you noticed today?" },
  { category: "daily", question: "What are you grateful for that you usually take for granted?" },
  { category: "daily", question: "What did you do today that your future self will thank you for?" },
  { category: "daily", question: "What's one thing you wish you could share with me right now?" },
  { category: "daily", question: "If you could teleport anywhere right now for 30 minutes, where would you go?" },
  { category: "daily", question: "What food have you been craving lately?" },
  { category: "daily", question: "What's something that's been making you anxious that you haven't said aloud?" },
  { category: "daily", question: "What part of your day do you look forward to the most?" },
  { category: "daily", question: "What's something you did today that you're a little proud of?" },
  { category: "daily", question: "Is there something you need from me right now that you haven't asked for?" },
  { category: "daily", question: "What's the funniest thing that happened to you this week?" },
  { category: "daily", question: "What's one thing you wish more people knew about your day-to-day life?" },
  { category: "daily", question: "What's a moment from your week you'd want to frame and keep?" },
  { category: "daily", question: "What kind of hug do you need right now?" },
  { category: "daily", question: "What was the first thought that crossed your mind when you woke up?" },
  { category: "daily", question: "If you could swap your day with anyone in the world, whose would you pick?" },
  { category: "daily", question: "What's the best conversation you had this week and why?" },
  { category: "daily", question: "What's one small thing I could do to make your day better right now?" },
  { category: "daily", question: "What's something happening in the world right now that's been on your mind?" },
  { category: "daily", question: "What made you feel like yourself today?" },
  { category: "daily", question: "What's a habit you're building that you're proud of?" },
  { category: "daily", question: "How did you use your body today — walked, danced, stretched, anything?" },
  { category: "daily", question: "What distracted you the most today?" },
  { category: "daily", question: "What's something you saw or read today that made you think of me?" },
  { category: "daily", question: "What's a smell that immediately takes you back to your childhood?" },
  { category: "daily", question: "If you could press pause on your life right now, what would you want to stay frozen forever?" },
  { category: "daily", question: "What's a decision you made today that you feel good about?" },
  { category: "daily", question: "What's something you wish you could unsay from this week?" },
  { category: "daily", question: "What's the next milestone you're quietly working toward?" },

  // ─── DEEP (50) ───────────────────────────────────────────
  { category: "deep", question: "What's the biggest lie you used to believe about yourself?" },
  { category: "deep", question: "What version of yourself are you scared of becoming?" },
  { category: "deep", question: "What's a belief you hold that most people in your life would disagree with?" },
  { category: "deep", question: "What's the most painful thing you've ever had to accept?" },
  { category: "deep", question: "What would you do differently if you knew no one would judge you?" },
  { category: "deep", question: "What does 'home' actually mean to you?" },
  { category: "deep", question: "Is there a version of your life you gave up that you still think about?" },
  { category: "deep", question: "What's the hardest apology you've ever had to give?" },
  { category: "deep", question: "What's something about yourself that took years to finally accept?" },
  { category: "deep", question: "When have you felt the most truly alone — even when surrounded by people?" },
  { category: "deep", question: "What dream did you let go of, and do you regret it?" },
  { category: "deep", question: "What's the most courageous thing you've ever done that nobody saw?" },
  { category: "deep", question: "If your childhood self met you today, what would they think?" },
  { category: "deep", question: "What's one emotion you're still learning how to handle?" },
  { category: "deep", question: "What's a question you're afraid to ask yourself?" },
  { category: "deep", question: "What's the one thing you could forgive yourself for but haven't yet?" },
  { category: "deep", question: "When did you last feel truly seen by another person?" },
  { category: "deep", question: "What would you do if you knew this was the last year of your life?" },
  { category: "deep", question: "What's the longest you've gone without being honest with yourself?" },
  { category: "deep", question: "What does love actually look like to you — not in theory, but in practice?" },
  { category: "deep", question: "What's your biggest fear about the future?" },
  { category: "deep", question: "What part of you do you hide most from the world?" },
  { category: "deep", question: "What's something you miss about a version of yourself from the past?" },
  { category: "deep", question: "How has distance shaped your definition of love?" },
  { category: "deep", question: "What's the kindest thing someone has ever said to you, and did you believe it?" },
  { category: "deep", question: "What's a fear you've never told anyone?" },
  { category: "deep", question: "Is there something you need more of in this relationship that you're scared to ask for?" },
  { category: "deep", question: "What's your definition of a wasted life?" },
  { category: "deep", question: "What has loving someone from afar taught you about yourself?" },
  { category: "deep", question: "What parts of your culture do you want to carry forward and which do you want to leave behind?" },
  { category: "deep", question: "What is the thing that, if it disappeared tomorrow, would break you?" },
  { category: "deep", question: "What's the most recent moment you felt completely, unreservedly at peace?" },
  { category: "deep", question: "Who are you when nobody is watching?" },
  { category: "deep", question: "What would you want said at your funeral?" },
  { category: "deep", question: "How much of who you are today was chosen vs inherited?" },
  { category: "deep", question: "When was the last time you changed your mind about something important?" },
  { category: "deep", question: "What do you wish you had said to someone who is no longer in your life?" },
  { category: "deep", question: "What's a version of success that actually excites you — not the version you perform for others?" },
  { category: "deep", question: "What is a wound that still hasn't fully healed?" },
  { category: "deep", question: "What's a sacrifice you made that no one ever thanked you for?" },
  { category: "deep", question: "Is there a relationship in your life you've been grieving in silence?" },
  { category: "deep", question: "What's one thing about yourself you're still figuring out?" },
  { category: "deep", question: "What would you do if you discovered you only had one more year to be with me?" },
  { category: "deep", question: "What has this relationship taught you about yourself that nothing else could?" },
  { category: "deep", question: "What's something you deeply value that you've never been able to fully articulate?" },
  { category: "deep", question: "What's the bravest thing you've done for love?" },
  { category: "deep", question: "If you wrote a letter to your future self in 10 years, what would be the most important thing you'd tell them?" },
  { category: "deep", question: "What's something you wish someone had told you when you were 16?" },
  { category: "deep", question: "When was the last time you did something that genuinely scared you?" },
  { category: "deep", question: "What's the thing you're most afraid I might stop loving about you one day?" },

  // ─── UNHINGED (50) ───────────────────────────────────────
  { category: "unhinged", question: "If animals could talk, which species would be the most insufferable?" },
  { category: "unhinged", question: "What would your villain origin story be, honestly?" },
  { category: "unhinged", question: "What's a hill you would absolutely die on, no matter how ridiculous?" },
  { category: "unhinged", question: "If you were a cult leader, what would your cult's thing be?" },
  { category: "unhinged", question: "What's the most chaotic thing you've done that you still think was justified?" },
  { category: "unhinged", question: "If your pet could speak for 60 seconds, what would they expose about you?" },
  { category: "unhinged", question: "What's a wild conspiracy theory you've entertained even briefly?" },
  { category: "unhinged", question: "If you could give a TED Talk on something completely unhinged, what would it be?" },
  { category: "unhinged", question: "What's the weirdest food combination you've eaten and actually enjoyed?" },
  { category: "unhinged", question: "If you had to eat the same meal every day for the rest of your life, what would it be?" },
  { category: "unhinged", question: "What's the most unhinged text you've ever almost sent?" },
  { category: "unhinged", question: "If you became a ghost, what three places would you haunt?" },
  { category: "unhinged", question: "What would your reality show be called and what would happen on it?" },
  { category: "unhinged", question: "If you could legally change your name to anything, what would it be?" },
  { category: "unhinged", question: "If the government was watching you for a week, what would confuse them most?" },
  { category: "unhinged", question: "What inanimate object would you get in a fight with if it came alive?" },
  { category: "unhinged", question: "If you could curse someone harmlessly, what would the curse be?" },
  { category: "unhinged", question: "What would your episode of a crime documentary be about?" },
  { category: "unhinged", question: "If your life was a nature documentary, what would the narrator say about you right now?" },
  { category: "unhinged", question: "What's your most deranged shower thought from this week?" },
  { category: "unhinged", question: "What fictional character would you trust the least in real life?" },
  { category: "unhinged", question: "If you were a final boss in a video game, what would your powers be?" },
  { category: "unhinged", question: "Which two fictional characters would have the most chaotic relationship?" },
  { category: "unhinged", question: "If you could only communicate in song lyrics for a full day, what genre would you choose?" },
  { category: "unhinged", question: "What would your evil twin do differently from you?" },
  { category: "unhinged", question: "What mundane task, if made into a competitive sport, would you dominate?" },
  { category: "unhinged", question: "If there was a Wikipedia article about you, what would the Controversies section say?" },
  { category: "unhinged", question: "What's something you genuinely believe about the universe that you can't prove?" },
  { category: "unhinged", question: "What's a skill you have that would be extremely useful in a zombie apocalypse?" },
  { category: "unhinged", question: "If you could add one rule to society that everyone had to follow, what would it be?" },
  { category: "unhinged", question: "What superpower would be the most annoying to have?" },
  { category: "unhinged", question: "If your life had a loading screen, what would the loading tip say?" },
  { category: "unhinged", question: "What would the warning label on you say?" },
  { category: "unhinged", question: "If you could only eat one cuisine for the rest of your life, but the catch is it has to be from a vending machine, what would you pick?" },
  { category: "unhinged", question: "What's a word or phrase that irrationally annoys you?" },
  { category: "unhinged", question: "If you could swap bodies with any animal for a day, but you have to go to work like that, what do you pick?" },
  { category: "unhinged", question: "What opinion do you hold that you're convinced will be proven right in 20 years?" },
  { category: "unhinged", question: "What's the most delusional version of yourself that you occasionally embody?" },
  { category: "unhinged", question: "If you had a theme song that played every time you entered a room, what would it be?" },
  { category: "unhinged", question: "What household chore, if turned into an Olympic sport, would you get a gold medal in?" },
  { category: "unhinged", question: "If your brain had a browser history, what tab would you be embarrassed about?" },
  { category: "unhinged", question: "What job in a medieval kingdom would you have had, realistically?" },
  { category: "unhinged", question: "If you had to describe your personality using only weather phenomena, what would you say?" },
  { category: "unhinged", question: "What's the most dramatic thing you've ever done over something genuinely not serious?" },
  { category: "unhinged", question: "If you were a limited edition snack, what would your flavor be and what would the package say?" },
  { category: "unhinged", question: "What conspiracy theory, if it turned out to be true, would you be least surprised by?" },
  { category: "unhinged", question: "What's the pettiest thought you had this week?" },
  { category: "unhinged", question: "If you had to choose a nemesis from history (any era), who would be most worthy of you?" },
  { category: "unhinged", question: "If you could make one thing illegal purely out of personal annoyance, what would it be?" },
  { category: "unhinged", question: "What's something you do when no one is watching that would confuse people?" },

  // ─── DEBATE (50) ─────────────────────────────────────────
  { category: "debate", question: "Is it possible to truly love someone you've never met in person?" },
  { category: "debate", question: "Long distance: relationship builder or relationship destroyer?" },
  { category: "debate", question: "Is jealousy ever healthy in a relationship?" },
  { category: "debate", question: "Can people really change, or do they just get better at hiding who they are?" },
  { category: "debate", question: "Is it okay to snoop through your partner's phone?" },
  { category: "debate", question: "Should couples share passwords to everything?" },
  { category: "debate", question: "Is it possible to have a genuine best friend of the opposite sex when you're in a relationship?" },
  { category: "debate", question: "Is it selfish to want to pursue your dreams if they conflict with your relationship?" },
  { category: "debate", question: "Should couples split finances 50/50 regardless of income?" },
  { category: "debate", question: "Is it okay to stay friends with your exes?" },
  { category: "debate", question: "Does love require sacrifice, or should it require no sacrifice at all?" },
  { category: "debate", question: "Is it ever okay to lie to protect your partner's feelings?" },
  { category: "debate", question: "Should you be allowed to have secrets in a relationship?" },
  { category: "debate", question: "Is social media toxic for romantic relationships?" },
  { category: "debate", question: "Do soulmates exist, or is love a choice you make every day?" },
  { category: "debate", question: "Can a relationship survive if one person wants kids and the other doesn't?" },
  { category: "debate", question: "Is flirting with someone else cheating?" },
  { category: "debate", question: "Should couples always be honest, even when the truth is brutal?" },
  { category: "debate", question: "Is it a red flag if someone has no close friends?" },
  { category: "debate", question: "Who should say 'I love you' first — and does it matter?" },
  { category: "debate", question: "Is love at first sight real, or just attraction?" },
  { category: "debate", question: "Is it healthy to be each other's 'everything'?" },
  { category: "debate", question: "Can someone fully know their partner if they haven't lived with them?" },
  { category: "debate", question: "Should you tell your partner every time someone flirts with you?" },
  { category: "debate", question: "Is there such a thing as too much communication in a relationship?" },
  { category: "debate", question: "Does distance actually make the heart grow fonder — or does it just make people grow apart?" },
  { category: "debate", question: "Should couples always go to bed at the same time?" },
  { category: "debate", question: "Is it a dealbreaker if someone doesn't share your religion or values?" },
  { category: "debate", question: "Can you truly forgive infidelity?" },
  { category: "debate", question: "Is the concept of 'the one' harmful to healthy relationships?" },
  { category: "debate", question: "Should you change yourself for the person you love?" },
  { category: "debate", question: "Is emotional cheating worse than physical cheating?" },
  { category: "debate", question: "Does compatibility matter more than chemistry?" },
  { category: "debate", question: "Is it possible to be in love with two people at the same time?" },
  { category: "debate", question: "Should couples share a bank account or keep finances separate?" },
  { category: "debate", question: "Is it normal to need breaks from the people you love?" },
  { category: "debate", question: "Does apologizing first mean you lose the argument?" },
  { category: "debate", question: "Is it better to be in a relationship with someone very similar or very different from you?" },
  { category: "debate", question: "Should you always tell your partner if you find someone else attractive?" },
  { category: "debate", question: "Can a relationship work if the love languages are completely opposite?" },
  { category: "debate", question: "Is vulnerability a strength or a weakness in a relationship?" },
  { category: "debate", question: "Should couples talk every single day, or is that too much?" },
  { category: "debate", question: "Is it okay for one partner to earn significantly more than the other?" },
  { category: "debate", question: "Is trust earned or given freely at the start of a relationship?" },
  { category: "debate", question: "Is maintaining a strong friendship with someone you used to date disrespectful to your current partner?" },
  { category: "debate", question: "Should couples have a plan B if the relationship ends — like a backup savings?" },
  { category: "debate", question: "Is overthinking the enemy of a good relationship?" },
  { category: "debate", question: "Do opposites really attract, or is that just a myth?" },
  { category: "debate", question: "Should 'I need space' ever be used as a reason to not communicate?" },
  { category: "debate", question: "Is it okay to vent about your partner to your friends?" },

  // ─── WOULD-YOU-RATHER (60) ──────────────────────────────
  { category: "would-you-rather", question: "Would you rather...", option_a: "Live in the city you love with a job you hate", option_b: "Live somewhere boring with a job you love" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Always be 10 minutes late", option_b: "Always be 20 minutes early" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Have your texts read by your parents", option_b: "Have your search history read to your coworkers" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Be stuck on a deserted island alone for a year", option_b: "Be stuck with someone you mildly dislike for a year" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Always know what people really think of you", option_b: "Never know but always be liked" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Always be overdressed", option_b: "Always be underdressed" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Have one great love story that ends", option_b: "Have many decent but forgettable relationships" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Be able to speak every language fluently", option_b: "Be able to play every instrument perfectly" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Never use social media again", option_b: "Never watch TV or movies again" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Always have to speak in rhymes", option_b: "Always have to speak in questions" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Be famous for something embarrassing", option_b: "Be completely unknown despite something amazing" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Never be able to lie", option_b: "Never be able to tell the truth" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Know the exact date of your death", option_b: "Never know but live ten fewer years" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Lose the ability to read", option_b: "Lose the ability to hear music" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Have a rewind button for life (one use only)", option_b: "Have a pause button for life (use anytime)" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Travel anywhere in the world for free but always alone", option_b: "Travel one place with the person you love, fully paid" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Give up coffee forever", option_b: "Give up your phone for 1 month" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Live 100 years as an average person", option_b: "Live 40 years as an extraordinary one" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Only eat food you cook yourself", option_b: "Never cook again and always eat out" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Know every secret about everyone around you", option_b: "Have everyone around you unable to keep your secrets" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Be 10 years ahead in your career", option_b: "Be 10 years younger with everything you know now" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Have unlimited money but no free time", option_b: "Have unlimited free time but barely enough money" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Be remembered after you die for one thing", option_b: "Be completely forgotten but have lived fully" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Be a morning person forever", option_b: "Be a night owl forever" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Never feel jealous again", option_b: "Never feel insecure again" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Be feared", option_b: "Be loved" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Live in a tiny house with a beautiful view", option_b: "Live in a huge house with no windows" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Text over calls forever", option_b: "Call over texts forever" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Live in a world where everyone is always honest", option_b: "Live in a world where everyone is kind but not always honest" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Have the ability to freeze time", option_b: "Have the ability to rewind time 10 minutes" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Know the answer to any question you ask", option_b: "Always have the perfect comeback" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Have to whisper everything you say", option_b: "Have to shout everything you say" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Lose all your photos and memories from the last 5 years", option_b: "Lose all your money and start over" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Be able to speak to animals", option_b: "Be able to speak to the dead" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Have no internet for a month", option_b: "Have no human interaction for a month" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Live without air conditioning forever", option_b: "Live without hot water forever" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Be stuck in traffic for 3 hours every day", option_b: "Have a 2-hour commute on public transport every day" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Always feel full and never feel hunger", option_b: "Always feel energized and never feel tired" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Have perfect memory", option_b: "Be able to selectively delete any memory" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Be the funniest person in any room", option_b: "Be the most interesting person in any room" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Win an Oscar", option_b: "Win a Nobel Prize" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Always be too hot", option_b: "Always be too cold" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Know every language on earth", option_b: "Be able to code anything you imagine" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Never have to sleep again", option_b: "Never have to eat again" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Have a personal chef", option_b: "Have a personal driver" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Go back to being 18 knowing what you know now", option_b: "Skip forward to age 40 and see your life" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Be able to see 10 minutes into the future", option_b: "Be able to change one past decision" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Live in a world with no conflict", option_b: "Live in a world with no disease" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Have everyone laugh at all your jokes", option_b: "Have everyone take you seriously all the time" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Live alone in a beautiful penthouse", option_b: "Live in a crowded but warm home full of people you love" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Forget the bad memories but lose some good ones too", option_b: "Keep everything, bad and good" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Be extremely rich but unknown", option_b: "Be famous worldwide but middle-class" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Have to dance every time music plays", option_b: "Have to sing everything you say" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Only be able to use one app on your phone forever", option_b: "Never be allowed to use headphones again" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Age normally in your mind but not your body", option_b: "Age normally in your body but not your mind" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Have one loyal best friend for life", option_b: "Have 100 close acquaintances who'd help you anytime" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Find true love but never be financially stable", option_b: "Be incredibly wealthy but always unlucky in love" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Be in a long distance relationship for 3 years with a guaranteed happy ending", option_b: "Be close together but uncertain" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Spend a week in the past", option_b: "Spend a week in the future" },
  { category: "would-you-rather", question: "Would you rather...", option_a: "Have your partner live right next door", option_b: "Have your partner live an 8-hour flight away but visit every month" },

  // ─── BRAIN TEASERS (70) ──────────────────────────────────
  { category: "brain-teaser", question: "I speak without a mouth and hear without ears. I have no body, but I come alive with wind. What am I?", option_a: "An echo", option_b: null },
  { category: "brain-teaser", question: "The more you take, the more you leave behind. What am I?", option_a: "Footsteps", option_b: null },
  { category: "brain-teaser", question: "I have cities, but no houses. I have mountains, but no trees. I have water, but no fish. I have roads, but no cars. What am I?", option_a: "A map", option_b: null },
  { category: "brain-teaser", question: "What gets wetter the more it dries?", option_a: "A towel", option_b: null },
  { category: "brain-teaser", question: "I am not alive, but I grow. I don't have lungs, but I need air. I don't have a mouth, but water kills me. What am I?", option_a: "Fire", option_b: null },
  { category: "brain-teaser", question: "The person who makes it, sells it. The person who buys it never uses it. The person who uses it doesn't know they are. What is it?", option_a: "A coffin", option_b: null },
  { category: "brain-teaser", question: "I have hands but cannot clap. What am I?", option_a: "A clock", option_b: null },
  { category: "brain-teaser", question: "What can run but never walks, has a mouth but never talks, has a head but never weeps, has a bed but never sleeps?", option_a: "A river", option_b: null },
  { category: "brain-teaser", question: "What has an eye but cannot see?", option_a: "A needle", option_b: null },
  { category: "brain-teaser", question: "I follow you all day long, but when night or rain comes, I am gone. What am I?", option_a: "Your shadow", option_b: null },
  { category: "brain-teaser", question: "What word contains 26 letters but only has three syllables?", option_a: "Alphabet", option_b: null },
  { category: "brain-teaser", question: "What can you hold in your right hand, but never in your left hand?", option_a: "Your left hand", option_b: null },
  { category: "brain-teaser", question: "What has many keys but cannot open a single lock?", option_a: "A piano", option_b: null },
  { category: "brain-teaser", question: "I'm tall when I'm young, and short when I'm old. What am I?", option_a: "A candle", option_b: null },
  { category: "brain-teaser", question: "What goes up when rain comes down?", option_a: "An umbrella", option_b: null },
  { category: "brain-teaser", question: "What breaks but never falls, and what falls but never breaks?", option_a: "Day breaks and night falls", option_b: null },
  { category: "brain-teaser", question: "A cowboy rode into town on Friday, stayed for three days, and left on Friday. How?", option_a: "His horse's name was Friday", option_b: null },
  { category: "brain-teaser", question: "What has four legs in the morning, two in the afternoon, and three in the evening?", option_a: "A human — crawls as a baby, walks as an adult, uses a cane when old", option_b: null },
  { category: "brain-teaser", question: "The more of me there is, the less you can see. What am I?", option_a: "Darkness", option_b: null },
  { category: "brain-teaser", question: "What room can no one enter?", option_a: "A mushroom", option_b: null },
  { category: "brain-teaser", question: "What is always in front of you but can't be seen?", option_a: "The future", option_b: null },
  { category: "brain-teaser", question: "I have branches but no fruit, trunk, or leaves. What am I?", option_a: "A bank", option_b: null },
  { category: "brain-teaser", question: "What can fill a room but takes up no space?", option_a: "Light", option_b: null },
  { category: "brain-teaser", question: "Which is heavier: a ton of bricks or a ton of feathers?", option_a: "Neither — they both weigh a ton", option_b: null },
  { category: "brain-teaser", question: "How many months have 28 days?", option_a: "All 12 of them", option_b: null },
  { category: "brain-teaser", question: "What invention lets you look right through a wall?", option_a: "A window", option_b: null },
  { category: "brain-teaser", question: "What word in the dictionary is spelled incorrectly?", option_a: "Incorrectly", option_b: null },
  { category: "brain-teaser", question: "What has a head and a tail but no body?", option_a: "A coin", option_b: null },
  { category: "brain-teaser", question: "What gets bigger the more you take away from it?", option_a: "A hole", option_b: null },
  { category: "brain-teaser", question: "What goes through cities and fields but never moves?", option_a: "A road", option_b: null },
  { category: "brain-teaser", question: "You are my brother, but I am not your brother. Who am I?", option_a: "Your sister", option_b: null },
  { category: "brain-teaser", question: "I am an odd number. Take away one letter and I become even. What number am I?", option_a: "Seven — remove the S and you get 'even'", option_b: null },
  { category: "brain-teaser", question: "What has a heart that doesn't beat?", option_a: "An artichoke", option_b: null },
  { category: "brain-teaser", question: "A doctor gives you 3 pills and tells you to take one every 30 minutes. How long until they're all taken?", option_a: "1 hour — take the 1st now, 2nd at 30 min, 3rd at 60 min", option_b: null },
  { category: "brain-teaser", question: "If there are three apples and you take away two, how many do you have?", option_a: "Two — the ones you took", option_b: null },
  { category: "brain-teaser", question: "What is so fragile that even saying its name breaks it?", option_a: "Silence", option_b: null },
  { category: "brain-teaser", question: "I'm light as a feather, but even the strongest person can't hold me for more than a few minutes. What am I?", option_a: "Breath", option_b: null },
  { category: "brain-teaser", question: "If you have me, you want to share me. If you share me, you don't have me. What am I?", option_a: "A secret", option_b: null },
  { category: "brain-teaser", question: "What do you see once in June, twice in November, but not at all in May?", option_a: "The letter 'e'", option_b: null },
  { category: "brain-teaser", question: "What can you keep after giving it to someone else?", option_a: "Your word", option_b: null },
  { category: "brain-teaser", question: "What's full of holes but still holds water?", option_a: "A sponge", option_b: null },
  { category: "brain-teaser", question: "What comes once in a minute, twice in a moment, but never in a thousand years?", option_a: "The letter M", option_b: null },
  { category: "brain-teaser", question: "What starts with E, ends with E, but only has one letter in it?", option_a: "An envelope", option_b: null },
  { category: "brain-teaser", question: "What building has the most stories?", option_a: "A library", option_b: null },
  { category: "brain-teaser", question: "I have no life, but I can die. What am I?", option_a: "A battery", option_b: null },
  { category: "brain-teaser", question: "What comes down but never goes up?", option_a: "Rain", option_b: null },
  { category: "brain-teaser", question: "What is so heavy that even the strongest person can't lift it? But if you write it, you can carry it.", option_a: "Debt", option_b: null },
  { category: "brain-teaser", question: "I am taken from a mine and shut up in a wooden case, from which I am never released, and yet I am used by everyone. What am I?", option_a: "A pencil", option_b: null },
  { category: "brain-teaser", question: "The more you cook it, the bigger it gets. What is it?", option_a: "Popcorn", option_b: null },
  { category: "brain-teaser", question: "What has legs but cannot walk?", option_a: "A table", option_b: null },
  { category: "brain-teaser", question: "What can travel around the world while staying in a corner?", option_a: "A stamp", option_b: null },
  { category: "brain-teaser", question: "I have a neck but no head, and I wear a cap. What am I?", option_a: "A bottle", option_b: null },
  { category: "brain-teaser", question: "What goes up and down but never moves?", option_a: "Stairs", option_b: null },
  { category: "brain-teaser", question: "If you drop me I'm sure to crack, but give me a smile and I'll always smile back. What am I?", option_a: "A mirror", option_b: null },
  { category: "brain-teaser", question: "What has 13 hearts but no other organs?", option_a: "A deck of cards", option_b: null },
  { category: "brain-teaser", question: "I'm not a bird, but I can fly. I'm not a clock, but I have hands. I'm not a human, but I have a face. What am I?", option_a: "An airplane clock — wait, just a clock!", option_b: null },
  { category: "brain-teaser", question: "What runs but doesn't walk, has a tongue but doesn't talk?", option_a: "A shoe", option_b: null },
  { category: "brain-teaser", question: "The more it dries, the wetter it gets. What is it?", option_a: "A towel", option_b: null },
  { category: "brain-teaser", question: "What do you throw out when you want to use it, but take in when you don't want to use it?", option_a: "An anchor", option_b: null },
  { category: "brain-teaser", question: "I have streets but no pavement, forests but no trees, and water but no fish. What am I?", option_a: "A map", option_b: null },
  { category: "brain-teaser", question: "What belongs to you but everyone else uses it more than you do?", option_a: "Your name", option_b: null },
  { category: "brain-teaser", question: "What flies without wings?", option_a: "Time", option_b: null },
  { category: "brain-teaser", question: "What is always coming but never arrives?", option_a: "Tomorrow", option_b: null },
  { category: "brain-teaser", question: "What can grow without soil, travel without legs, and warm without fire?", option_a: "The sun", option_b: null },
  { category: "brain-teaser", question: "What disappears as soon as you say its name?", option_a: "Silence", option_b: null },
  { category: "brain-teaser", question: "Two mothers and two daughters went out to eat, and each had a meal. Only three meals were paid for. How?", option_a: "They were a grandmother, a mother, and a daughter — three people", option_b: null },
  { category: "brain-teaser", question: "What has one eye but can't see anything at all?", option_a: "A storm (the eye of a storm)", option_b: null },
  { category: "brain-teaser", question: "What's black when you buy it, red when you use it, and grey when you throw it away?", option_a: "Charcoal", option_b: null },
  { category: "brain-teaser", question: "I am always hungry and must always be fed. The finger I touch turns red. What am I?", option_a: "Fire", option_b: null },
  { category: "brain-teaser", question: "What connects two people but only touches one?", option_a: "A wedding ring", option_b: null },

  // ─── NEVER-HAVE-I-EVER (50) ──────────────────────────────
  { category: "never-have-i-ever", question: "Never have I ever sent a risky text to the wrong person." },
  { category: "never-have-i-ever", question: "Never have I ever stayed up all night talking to someone I liked." },
  { category: "never-have-i-ever", question: "Never have I ever pretended not to see a message to buy time." },
  { category: "never-have-i-ever", question: "Never have I ever had a crush on a teacher or professor." },
  { category: "never-have-i-ever", question: "Never have I ever stalked someone's profile before meeting them." },
  { category: "never-have-i-ever", question: "Never have I ever cried during a movie and pretended not to." },
  { category: "never-have-i-ever", question: "Never have I ever texted someone about themselves while in the same room." },
  { category: "never-have-i-ever", question: "Never have I ever googled myself." },
  { category: "never-have-i-ever", question: "Never have I ever told a lie so convincingly I almost believed it myself." },
  { category: "never-have-i-ever", question: "Never have I ever rehearsed an argument in the shower." },
  { category: "never-have-i-ever", question: "Never have I ever had a dream about someone and acted weird around them afterward." },
  { category: "never-have-i-ever", question: "Never have I ever pretended to be busy to avoid plans." },
  { category: "never-have-i-ever", question: "Never have I ever liked something accidentally on someone's old profile." },
  { category: "never-have-i-ever", question: "Never have I ever screenshotted a conversation to show someone else." },
  { category: "never-have-i-ever", question: "Never have I ever ghosted someone I actually liked because I got scared." },
  { category: "never-have-i-ever", question: "Never have I ever faked being sick to get out of something." },
  { category: "never-have-i-ever", question: "Never have I ever had feelings for someone in a relationship." },
  { category: "never-have-i-ever", question: "Never have I ever deleted a text thread out of embarrassment." },
  { category: "never-have-i-ever", question: "Never have I ever pretended to laugh at something I didn't understand." },
  { category: "never-have-i-ever", question: "Never have I ever driven somewhere impulsively just because of a feeling." },
  { category: "never-have-i-ever", question: "Never have I ever said 'I love you' first and immediately regretted it." },
  { category: "never-have-i-ever", question: "Never have I ever kept something from a partner to protect them." },
  { category: "never-have-i-ever", question: "Never have I ever told a secret I promised to keep." },
  { category: "never-have-i-ever", question: "Never have I ever laughed at something inappropriate at the worst moment." },
  { category: "never-have-i-ever", question: "Never have I ever written a letter I never sent." },
  { category: "never-have-i-ever", question: "Never have I ever had a moment that felt so good it scared me." },
  { category: "never-have-i-ever", question: "Never have I ever been genuinely starstruck." },
  { category: "never-have-i-ever", question: "Never have I ever missed someone so much it physically hurt." },
  { category: "never-have-i-ever", question: "Never have I ever told someone I was on my way when I hadn't left yet." },
  { category: "never-have-i-ever", question: "Never have I ever fallen asleep on a call with someone I love." },
  { category: "never-have-i-ever", question: "Never have I ever cried happy tears over something small." },
  { category: "never-have-i-ever", question: "Never have I ever apologized without actually being sorry." },
  { category: "never-have-i-ever", question: "Never have I ever eaten an entire meal I didn't enjoy just to be polite." },
  { category: "never-have-i-ever", question: "Never have I ever binged an entire TV series in one sitting." },
  { category: "never-have-i-ever", question: "Never have I ever said something mean about someone and immediately felt terrible." },
  { category: "never-have-i-ever", question: "Never have I ever judged someone's playlist judgment-free and then judged them." },
  { category: "never-have-i-ever", question: "Never have I ever planned a whole argument in my head before having it." },
  { category: "never-have-i-ever", question: "Never have I ever bought something expensive and hidden it from people." },
  { category: "never-have-i-ever", question: "Never have I ever talked to a plant or given it a name." },
  { category: "never-have-i-ever", question: "Never have I ever cried in a bathroom so no one would see." },
  { category: "never-have-i-ever", question: "Never have I ever re-read old messages just to feel something." },
  { category: "never-have-i-ever", question: "Never have I ever given terrible advice confidently." },
  { category: "never-have-i-ever", question: "Never have I ever said 'I'm not mad' when I was absolutely furious." },
  { category: "never-have-i-ever", question: "Never have I ever eaten food off the floor and called it fine." },
  { category: "never-have-i-ever", question: "Never have I ever used someone's name wrong the entire time I knew them." },
  { category: "never-have-i-ever", question: "Never have I ever stayed in a situation too long just to avoid awkwardness." },
  { category: "never-have-i-ever", question: "Never have I ever had a phase I'm mildly embarrassed about now." },
  { category: "never-have-i-ever", question: "Never have I ever laughed so hard I cried at completely the wrong time." },
  { category: "never-have-i-ever", question: "Never have I ever needed someone and refused to say it." },
  { category: "never-have-i-ever", question: "Never have I ever daydreamed so hard about the future that I forgot where I was." },
];

export async function GET() {
  const supabase = await createClient();

  // 1. Fetch all existing questions so we don't insert duplicates
  const { data: existing, error: fetchError } = await supabase
    .from("prompts")
    .select("question");

  if (fetchError) {
    return NextResponse.json({ success: false, error: fetchError.message }, { status: 500 });
  }

  const existingSet = new Set((existing ?? []).map((r: { question: string }) => r.question.trim().toLowerCase()));

  // 2. Filter to only new prompts
  const allRecords = PROMPTS.map((p) => ({
    category: p.category,
    question: p.question,
    option_a: p.option_a ?? null,
    option_b: p.option_b ?? null,
    is_active: true,
  }));

  const newRecords = allRecords.filter(
    (r) => !existingSet.has(r.question.trim().toLowerCase())
  );

  if (newRecords.length === 0) {
    return NextResponse.json({
      success: true,
      inserted: 0,
      skipped: allRecords.length,
      message: "All prompts already exist in the database. Nothing to insert.",
    });
  }

  // 3. Insert in batches of 50
  const batchSize = 50;
  let inserted = 0;
  const errors: string[] = [];

  for (let i = 0; i < newRecords.length; i += batchSize) {
    const batch = newRecords.slice(i, i + batchSize);
    const { error } = await supabase.from("prompts").insert(batch);
    if (error) {
      errors.push(`Batch ${Math.floor(i / batchSize) + 1}: ${error.message}`);
    } else {
      inserted += batch.length;
    }
  }

  return NextResponse.json({
    success: true,
    inserted,
    skipped: allRecords.length - newRecords.length,
    total_in_db_after: (existing?.length ?? 0) + inserted,
    errors: errors.length > 0 ? errors : undefined,
  });
}
